# -*- coding: utf-8 -*-
"""Codigo Proyecto PDI (Sin Librerías).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYF-Cv9c0xd5w4gR3G6spYOAYnETfYMJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import zipfile

# FUNCIÓN DE CLASIFICACIÓN GENERAL

def clasificar_imagen(mask, umbral=0.15):
    area = np.sum(mask > 0) / mask.size

    if area > umbral:
        return "ENFERMA", area
    else:
        return "SANA", area

# FUNCIONES MANUALES

# Filtro Gaussiano (convolución)
def gaussian_filter(image, kernel_size=5, sigma=1):

    # Crear kernel gaussiano
    ax = np.linspace(-(kernel_size // 2), kernel_size // 2, kernel_size)
    xx, yy = np.meshgrid(ax, ax)
    kernel = np.exp(-(xx**2 + yy**2) / (2 * sigma**2))
    kernel = kernel / np.sum(kernel)

    # Padding
    pad = kernel_size // 2
    padded = np.pad(image, ((pad,pad),(pad,pad),(0,0)), mode='reflect')

    output = np.zeros_like(image)

    # Convolución manual
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            for c in range(3):
                region = padded[i:i+kernel_size, j:j+kernel_size, c]
                output[i,j,c] = np.sum(region * kernel)

    return output.astype(np.uint8)


# Umbral manual tipo inRange
def threshold_range(hsv, lower, upper):
    mask = np.zeros((hsv.shape[0], hsv.shape[1]), dtype=np.uint8)

    for i in range(hsv.shape[0]):
        for j in range(hsv.shape[1]):
            h, s, v = hsv[i,j]

            if (lower[0] <= h <= upper[0] and
                lower[1] <= s <= upper[1] and
                lower[2] <= v <= upper[2]):
                mask[i,j] = 255

    return mask

# 1. DESCOMPRIMIR DATASET

zip_path = "/content/Tomato___Dataset.zip"
extract_path = "/content/Tomato___Dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset descomprimido correctamente")


# 2. DEFINIR RUTAS

ruta_early = "/content/Tomato___Dataset/Tomato___Early_blight"
ruta_healthy = "/content/Tomato___Dataset/Tomato___healthy"

# 3. CARGAR IMÁGENES

img_early = cv2.imread(os.path.join(ruta_early, os.listdir(ruta_early)[0]))
img_healthy = cv2.imread(os.path.join(ruta_healthy, os.listdir(ruta_healthy)[0]))

img_early = cv2.cvtColor(img_early, cv2.COLOR_BGR2RGB)
img_healthy = cv2.cvtColor(img_healthy, cv2.COLOR_BGR2RGB)

# 4. PREPROCESAMIENTO

# Aplicación de filtro Gaussiano manual
blur_early = gaussian_filter(img_early)
blur_healthy = gaussian_filter(img_healthy)

# 5. TRANSFORMACIÓN HSV

hsv_early = cv2.cvtColor(blur_early, cv2.COLOR_RGB2HSV)
hsv_healthy = cv2.cvtColor(blur_healthy, cv2.COLOR_RGB2HSV)

# 6. AISLAR LA HOJA (VERDE)

lower_green = np.array([35, 40, 40])
upper_green = np.array([85, 255, 255])

mask_leaf_early = threshold_range(hsv_early, lower_green, upper_green)
mask_leaf_healthy = threshold_range(hsv_healthy, lower_green, upper_green)


# 7. DETECTAR ENFERMEDAD

lower_disease = np.array([5, 50, 50])
upper_disease = np.array([30, 255, 200])

mask_color_early = threshold_range(hsv_early, lower_disease, upper_disease)
mask_color_healthy = threshold_range(hsv_healthy, lower_disease, upper_disease)

# Detección de zonas oscuras
mask_dark_early = (hsv_early[:,:,2] < 120).astype(np.uint8) * 255
mask_dark_healthy = (hsv_healthy[:,:,2] < 120).astype(np.uint8) * 255

mask_disease_early = np.maximum(mask_color_early, mask_dark_early)
mask_disease_healthy = np.maximum(mask_color_healthy, mask_dark_healthy)

# 8. COMBINAR (SOLO EN LA HOJA)

mask_early = np.minimum(mask_disease_early, mask_leaf_early)
mask_healthy = np.minimum(mask_disease_healthy, mask_leaf_healthy)

# 9. MORFOLOGÍA SIMPLE

kernel = np.ones((3,3))

def erosion(img):
    output = np.zeros_like(img)
    for i in range(1, img.shape[0]-1):
        for j in range(1, img.shape[1]-1):
            region = img[i-1:i+2, j-1:j+2]
            output[i,j] = np.min(region)
    return output

mask_early = erosion(mask_early)
mask_healthy = erosion(mask_healthy)

# 10. EXTRACCIÓN DE CARACTERÍSTICAS

# Se calcula el porcentaje de área afectada respecto al total de la imagen
area_early = np.sum(mask_early > 0) / mask_early.size
area_healthy = np.sum(mask_healthy > 0) / mask_healthy.size

print("\nResultados:")
print("Área afectada (IMAGEN 1):", round(area_early, 4))
print("Área afectada (IMAGEN 2):", round(area_healthy, 4))

clase_early, area_early = clasificar_imagen(mask_early)
clase_healthy, area_healthy = clasificar_imagen(mask_healthy)

print("\nResultados:")
print("Imagen 1 :", clase_early, "| Área:", round(area_early,4))
print("Imagen 2 :", clase_healthy, "| Área:", round(area_healthy,4))



# 11. VISUALIZACIÓN

plt.figure(figsize=(10,8))

# EARLY
plt.subplot(2,2,1)
plt.title(f"Imagen 1 - {clase_early}")
plt.imshow(img_early)
plt.axis("off")

plt.subplot(2,2,2)
plt.title("Segmentación")
plt.imshow(mask_early, cmap='gray')
plt.axis("off")

# HEALTHY
plt.subplot(2,2,3)
plt.title(f"Imagen 2 - {clase_healthy}")
plt.imshow(img_healthy)
plt.axis("off")

plt.subplot(2,2,4)
plt.title("Segmentación")
plt.imshow(mask_healthy, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()