# -*- coding: utf-8 -*-
"""Codigo Proyecto PDI (Con Librerías).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FyXjrYmdpiFlRa8LSzpUKPSGo4AcZ0u
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import zipfile

# FUNCIÓN DE CLASIFICACIÓN GENERAL

def clasificar_imagen(mask, umbral=0.15):
    area = np.sum(mask > 0) / mask.size

    if area > umbral:
        return "ENFERMA", area
    else:
        return "SANA", area

# 1. DESCOMPRIMIR DATASET

zip_path = "/content/Tomato___Dataset.zip"
extract_path = "/content/Tomato___Dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset descomprimido correctamente")


# 2. DEFINIR RUTAS

ruta_early = "/content/Tomato___Dataset/Tomato___Early_blight"
ruta_healthy = "/content/Tomato___Dataset/Tomato___healthy"


# 3. CARGAR IMÁGENES

# Se carga una imagen de cada clase (enferma y sana)
img_early = cv2.imread(os.path.join(ruta_early, os.listdir(ruta_early)[0]))
img_healthy = cv2.imread(os.path.join(ruta_healthy, os.listdir(ruta_healthy)[0]))

# Conversión de BGR (OpenCV) a RGB para correcta visualización
img_early = cv2.cvtColor(img_early, cv2.COLOR_BGR2RGB)
img_healthy = cv2.cvtColor(img_healthy, cv2.COLOR_BGR2RGB)


# 4. PREPROCESAMIENTO

# Aplicación de filtro Gaussiano para reducir ruido en la imagen
blur_early = cv2.GaussianBlur(img_early, (5,5), 0)
blur_healthy = cv2.GaussianBlur(img_healthy, (5,5), 0)


# 5. TRANSFORMACIÓN HSV

# Conversión al espacio HSV para separar color e intensidad
hsv_early = cv2.cvtColor(blur_early, cv2.COLOR_RGB2HSV)
hsv_healthy = cv2.cvtColor(blur_healthy, cv2.COLOR_RGB2HSV)


# 6. AISLAR LA HOJA (VERDE)

# Se define un rango para detectar únicamente las zonas verdes (hoja)
lower_green = np.array([35, 40, 40])
upper_green = np.array([85, 255, 255])

mask_leaf_early = cv2.inRange(hsv_early, lower_green, upper_green)
mask_leaf_healthy = cv2.inRange(hsv_healthy, lower_green, upper_green)


# 7. DETECTAR ENFERMEDAD

# Se detectan zonas marrones/amarillas características de la enfermedad
lower_disease = np.array([5, 50, 50])
upper_disease = np.array([30, 255, 200])

mask_color_early = cv2.inRange(hsv_early, lower_disease, upper_disease)
mask_color_healthy = cv2.inRange(hsv_healthy, lower_disease, upper_disease)

# Detección adicional de zonas oscuras (baja intensidad)
# Esto permite capturar manchas que no tienen un color específico
mask_dark_early = hsv_early[:,:,2] < 120
mask_dark_healthy = hsv_healthy[:,:,2] < 120

# Conversión a formato binario (0 o 255)
mask_dark_early = mask_dark_early.astype(np.uint8) * 255
mask_dark_healthy = mask_dark_healthy.astype(np.uint8) * 255

# Combinación de ambas detecciones (color + oscuridad)
mask_disease_early = cv2.bitwise_or(mask_color_early, mask_dark_early)
mask_disease_healthy = cv2.bitwise_or(mask_color_healthy, mask_dark_healthy)


# 8. COMBINAR (SOLO EN LA HOJA)

# Se restringe la detección únicamente a la región de la hoja
mask_early = cv2.bitwise_and(mask_disease_early, mask_leaf_early)
mask_healthy = cv2.bitwise_and(mask_disease_healthy, mask_leaf_healthy)

# Suavizado para eliminar ruido pequeño
mask_early = cv2.GaussianBlur(mask_early, (5,5), 0)

# Erosión para eliminar detecciones falsas muy grandes o difusas
mask_early = cv2.erode(mask_early, np.ones((3,3), np.uint8), iterations=1)


# 9. MORFOLOGÍA (MEJORADA)

# Se aplica cierre morfológico para unir regiones cercanas
kernel = np.ones((5,5), np.uint8)

mask_early = cv2.morphologyEx(mask_early, cv2.MORPH_CLOSE, kernel)
mask_healthy = cv2.morphologyEx(mask_healthy, cv2.MORPH_CLOSE, kernel)

# Eliminar ruido pequeño (componentes pequeños)
num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask_healthy)

min_area = 500  # ajustable

clean_mask = np.zeros_like(mask_healthy)

for i in range(1, num_labels):
    if stats[i, cv2.CC_STAT_AREA] > min_area:
        clean_mask[labels == i] = 255

mask_healthy = clean_mask

# 10. EXTRACCIÓN DE CARACTERÍSTICAS

# Se calcula el porcentaje de área afectada respecto al total de la imagen
area_early = np.sum(mask_early > 0) / mask_early.size
area_healthy = np.sum(mask_healthy > 0) / mask_healthy.size

print("\nResultados:")
print("Área afectada (Early Blight):", round(area_early, 4))
print("Área afectada (Healthy):", round(area_healthy, 4))

clase_early, area_early = clasificar_imagen(mask_early)
clase_healthy, area_healthy = clasificar_imagen(mask_healthy)

print("\nResultados:")
print("Imagen 1 :", clase_early, "| Área:", round(area_early,4))
print("Imagen 2 :", clase_healthy, "| Área:", round(area_healthy,4))

# 11. VISUALIZACIÓN

plt.figure(figsize=(10,8))

# EARLY
plt.subplot(2,2,1)
plt.title(f"Imagen 1 - {clase_early}")
plt.imshow(img_early)
plt.axis("off")

plt.subplot(2,2,2)
plt.title("Segmentación")
plt.imshow(mask_early, cmap='gray')
plt.axis("off")

# HEALTHY
plt.subplot(2,2,3)
plt.title(f"Imagen 2 - {clase_healthy}")
plt.imshow(img_healthy)
plt.axis("off")

plt.subplot(2,2,4)
plt.title("Segmentación")
plt.imshow(mask_healthy, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()